### ISSUE TITLE
Configure prowlarr failing with vpn service

### ISSUE THREAD

**Issue by Qinusty** [navilg/media-stack#23]
Configure prowlarr docs networking seems incorrect given access to radarr over localhost:7878 is not accessable on the vpn service network. https://github.com/navilg/media-stack/tree/main#configure-prowlarr

![image](https://github.com/navilg/media-stack/assets/7274845/ccd4c25c-0b6f-4216-a517-55cd412d3666)

I've tried various hostnames instead of localhost but looks like something is slightly misconfigured.

**Comment by navilg** [comment]
Use http://radarr:7878

**Comment by Qinusty** [comment]
![image](https://github.com/navilg/media-stack/assets/7274845/deb833e6-b490-4d88-8687-d50c760e56b6)

```yml
radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:4.7.5
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"
    
prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.6.3

    # Uncomment below if vpn is enabled
    depends_on:               # Uncomment this line if vpn is enabled
      - vpn                   # Uncomment this line if vpn is enabled
    network_mode: service:vpn # Uncomment this line if vpn is enabled

    # networks:               # Comment this line if vpn is enabled
    #   - mynetwork           # Comment this line if vpn is enabled
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config

    # Comment below ports if VPN is enabled.
    # ports:
    #   - 9696:9696
    restart: unless-stopped
```

**Comment by navilg** [comment]
Let me check this on weekend

**Comment by lochot** [comment]
@navilg  thank for this repo ! i am trying it and i love it :)

[Qinusty] -> i had the same problem behind my vpn, just go in your radarr container check it's ip, and use it in place of localhost
to enter your docker container
```bash
docker-compose exec radarr bash
```
to show ip of it
```bash
ifconfig
```
to exit from the container (do not stop the container)
```bash
exit
```

**Comment by navilg** [comment]
Thanks @lochot I am able to replicate the issue.
It will work when you add IP address of radarr instead of service name or if you have public DNS (with SSL configured), use your radarr HTTPS url instead. Meanwhile I will look into the issue

**Comment by navilg** [comment]
This is because prowlarr and qBittorrent are behind VPN and when you hit http://radarr:7878 It is hitting from VPN server and not from docker network. So, It is not able to resolve it. Need to find out how to make it resolve local dns.

**Comment by MulverineX** [comment]
Unfortunately for some folks (myself included), even if this gets fixed there's an upstream issue in the way too https://github.com/qdm12/gluetun/issues/788.

**Comment by sbarkar** [comment]
Okay, please ignore anything I said in the last message. 

I made it work via the Nginx proxy. Please see my code in [the forked repo](https://github.com/sbarkar/media-stack). I have yet to do the documentation properly.

![Screenshot 2023-08-31 at 19 24 51](https://github.com/navilg/media-stack/assets/47544355/63487164-4c20-47c8-8fe9-8bc14a628d6b)

![Screenshot 2023-08-31 at 19 25 13](https://github.com/navilg/media-stack/assets/47544355/e76a3736-ff78-4630-a1bf-f258b97bc8d3)

The problem is that the connectivity needs to be improved, which makes Prowlarr inefficient. It barely syncs the Indexers. Sometimes, if it fails to sync and I force it a few times, it just goes into "cooldown" mode and does not let you manually force refresh until some time passes. In reality, I have only a few indices synced in Radarr and none in Sonarr even if the tests in the UI are successful. Any ideas on what we could do to make it more stable?

**Comment by MulverineX** [comment]
Here's my working setup https://gist.github.com/MulverineX/00a56505908c63d679188ef984820c54

**Comment by navilg** [comment]
> Here's my working setup https://gist.github.com/MulverineX/00a56505908c63d679188ef984820c54

It should work when all services are behind VPN

**Comment by bl4ko** [comment]
This is a well known gluetun's [issue](https://github.com/qdm12/gluetun/issues/281) and its workaround is documented on [glutun-wiki](https://github.com/qdm12/gluetun-wiki/blob/main/setup/inter-containers-networking.md#between-a-gluetun-connected-container-and-another-container).

Basically you should define static ip addresses for all services that are not part of the vpn stack (`network_mode: service:vpn`).

I have written a simple working example for the services `radarr` (not part of the stack), `gluetun` and `prowlarr`:

- Create a bridged network `docker network create --subnet=172.18.0.0/16 mynetwork`
- Set a static ip (eg. 172.18.0.22) for the `radarr` service

```yaml
name: test
services:
  vpn:
    image: docker.io/qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=Slovenia
    networks:
      - mynetwork
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9696:9696
    restart: "unless-stopped"

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - prowlar_config:/config
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    networks:
      mynetwork:
        ipv4_address: 172.18.0.22
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - radarr_config:/config
      - torrent_volume:/downloads:z
    restart: "unless-stopped"

volumes:
  prowlar_config:
  radarr_config:
  torrent_volume:


networks:
  mynetwork:
    external: true

```

- Now inside `prowlarr` we can access `radarr` with that static ip:

![test](https://github.com/navilg/media-stack/assets/83308880/a52b46e4-613b-4173-a223-f8e8ad49ca9d)

- you can now use this workaround for all other services that are not part of the vpn stack

**Comment by navilg** [comment]
Added the feature to enable static IP for radarr and sonnar. Since prowlarr is accessing the radarr and sonarr through VPN network, It won't be able to access them with service name or localhost.

d044f5dba1e5eb7bd57cb4fe6579fffb0b626c17

**Comment by jpmckearin** [comment]
I am not sure if this is advised, but I found that if you add a custom bridge network with the subnet/gateway ip specified and add that network to the gluetun service then you can set the `Radaar Server` config to `http://${NET_GATEWAY}:${RADAAR_PORT}` in the config for Prowlarr. This seems to remove the need to set a static ip for the Radaar server (as evidenced by the screenshot below showing the test succeeded). 

### .env
``` sh
NET_GATEWAY="172.29.0.1"
NET_SUBNET="172.29.0.0/24"
RADAAR_PORT=7878
```

### docker-compose.yml
``` yml
networks:
  servarr:
    ipam:
      driver: default
      config:
        - subnet: ${NET_SUBNET}
          gateway: ${NET_GATEWAY}
services:
  gluetun:
    # collapsed configs...
    ports:
      # collapsed configs...
      - 9696:9696/tcp # prowlarr
    networks:
      - servarr
  prowlarr:
    # collapsed configs...
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
  radarr:
    # collapsed configs...
    ports:
      - ${RADAAR_PORT}:7878
    networks:
      - servarr
    restart: unless-stopped
```

<img width="706" alt="image" src="https://github.com/navilg/media-stack/assets/6679168/bfc3c0c4-47b2-475b-9a33-1c5f98b70e7c">
