### ISSUE TITLE
[BUG] invalid IPv4 address - docker compose

### ISSUE THREAD

**Issue by huseyinkogo** [navilg/media-stack#36]
**Describe the bug**
I can't get the media stack working. getting the following error;  _`Error response from daemon: invalid IPv4 address: sonarr-container-static-ip`_

Also i have nfs mount for the downloads of `/mnt/Downloads/qBittorent` i hope thats fine too with this docker compose.

**Screenshots**
![image](https://github.com/navilg/media-stack/assets/76049382/586274ad-21f8-4288-a1f5-ba7d374e2a47)

**Platforms (please complete the following information):**
 - Debian 12 VM
 - Docker version 24.0.7

**Docker compose file**

```yaml
version: "3.9"
name: media-stack
services:
  vpn:
    profiles: ["vpn"]
    container_name: vpn
    image: qmcgaw/gluetun:v3.36.0
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-mullvad}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Australia}
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES="
    networks:
      - mynetwork
    ports:
      # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      # prowlarr ports
      - 9696:9696
    restart: "unless-stopped"

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:4.6.2
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=5080
    volumes:
      - ./qbittorrent-config:/config
      - /mnt/Downloads/qBittorent:/downloads
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.2.6
    networks:
      mynetwork:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    ports:
      - 7878:7878
    volumes:
      - ./radarr-config:/config
      - /mnt/Downloads/qBittorent:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    networks:
      mynetwork:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./sonarr-config:/config
      - /mnt/Downloads/qBittorent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.11.4
    depends_on:
      - vpn                   
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./prowlarr-config:/config
    restart: unless-stopped

volumes:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  qbittorrent-config:

networks:
  mynetwork:
    external: true
```

**Additional context**
