### ISSUE TITLE
[FEATURE REQUEST]  FlareSolverr

### ISSUE THREAD

**Issue by anton-dealmeida** [navilg/media-stack#54]
**Is your feature request related to a problem? Please describe.**
I found that Prowlarr recommends adding FlareSolverr in order to be able many of the public indices.
https://wiki.servarr.com/prowlarr/faq#can-i-use-flaresolverr-indexers

**Describe the solution you'd like**
Could we potentially look at adding FlareSolverr to this stack?

**Describe alternatives you've considered**
I'm currently avoiding those indices but would be cool to use and track them.

Some ideas:
```yaml
version: "3.9"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - mynetwork
```
