### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Keenan-Nicholson** [navilg/media-stack#63]
**Describe the bug**
Prowlarr does not need to run through the VPN. Only the download client (qbittorrent) should be have the tag
`network_mode: service:vpn`

**Expected behavior**
If running Prowlarr through the vpn indexers fail at a very high rate due to DNS issues.

**Docker compose file**

```yaml
  prowlarr:
    profiles: ["vpn", "no-vpn"]
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
   
    network_mode: service:vpn # Uncomment this line if vpn is enabled

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config

    restart: unless-stopped
```

**Additional context**
I tried for quite a while to diagnose why I was getting DNS errors. I realized that Prowlarr does not need to, and actually should NOT be using the `service:vpn` tag as it is not dealing with sensitive information. 

The download client is the only service that NEEDS to be inside this container.

For 2 weeks my I could not download a single movie or tv show, as soon as I took Prowlarr out of the vpn everything worked.

Please let me know if I can make a pull request to the docker-compose.yml and update the readme to reflect these suggested changes.
