### ISSUE TITLE
Getting working on a rasp pi on arm64

### ISSUE THREAD

**Issue by willwade** [navilg/media-stack#66]
I had to do 

```bash
export DOCKER_DEFAULT_PLATFORM=linux/arm64
docker compose --profile vpn up -d
```

stick all your env vars in a .env 

then 

my docker-compose.yml

```

name: media-stack
services:

  vpn:
    profiles: ["vpn"]
    container_name: vpn
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
    devices:
      - /dev/net/tun
    networks:
      - mynetwork
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  qbittorrent:
    profiles: ["vpn", "no-vpn"]
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.0.4
    depends_on:
      vpn:
        condition: service_started
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    restart: unless-stopped

  radarr:
    profiles: ["vpn", "no-vpn"]
    container_name: radarr
    image: hotio/radarr
    platform: linux/arm64
    networks:
      mynetwork:
        ipv4_address: ${RADARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: unless-stopped

  sonarr:
    profiles: ["vpn", "no-vpn"]
    container_name: sonarr
    image: hotio/sonarr
    platform: linux/arm64
    networks:
      mynetwork:
        ipv4_address: ${SONARR_STATIC_CONTAINER_IP}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    profiles: ["vpn", "no-vpn"]
    container_name: prowlarr
    image: hotio/prowlarr
    platform: linux/arm64
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    profiles: ["vpn", "no-vpn"]
    image: fallenbagel/jellyseerr
    platform: linux/arm64
    container_name: jellyseerr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  jellyfin:
    profiles: ["vpn", "no-vpn"]
    image: jellyfin/jellyfin
    platform: linux/arm64
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  recommendarr:
    profiles: ["recommendarr"]
    container_name: recommendarr
    image: tannermiddleton/recommendarr:v1.2.70
    networks:
      - mynetwork
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=3000
      - PUBLIC_URL=https://localhost:3000
    volumes:
      - recommendarr-data:/app/server/data
    ports:
      - 3000:3000
    restart: unless-stopped

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jellyseerr-config:
  recommendarr-data:

networks:
  mynetwork:
    external: true


```
